name: Deploy Grocify to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            cd /home/ubuntu

            # Clone repo if not exists
            if [ ! -d "Grocify" ]; then
              git clone https://github.com/AbhiJeetSoni22/Grocify.git
            fi

            cd Grocify
            git pull origin main

            # ===== BACKEND =====
            cd backend
            npm install

            export NODE_ENV=${{ secrets.NODE_ENV }}
            export MONGODB_URI="${{ secrets.MONGODB_URI }}"
            export JWT_SECRET="${{ secrets.JWT_SECRET }}"
            export SELLER_EMAIL="${{ secrets.SELLER_EMAIL }}"
            export SELLER_PASSWORD="${{ secrets.SELLER_PASSWORD }}"
            export CLOUDINARY_CLOUD_NAME="${{ secrets.CLOUDINARY_CLOUD_NAME }}"
            export CLOUDINARY_API_KEY="${{ secrets.CLOUDINARY_API_KEY }}"
            export CLOUDINARY_API_SECRET="${{ secrets.CLOUDINARY_API_SECRET }}"

            pm2 delete backend || true
            pm2 start backend/ecosystem.config.cjs
            pm2 save

            # ===== FRONTEND (VITE) =====
            cd ../frontend
            npm install
            npm run build

            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html
            sudo systemctl restart nginx
          EOF
